In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf

# Import our input dataset
diabetes_df = pd.read_csv('diabetes.csv')
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
# Remove diabetes outcome target from features data
y = diabetes_df.Outcome
X = diabetes_df.drop(columns="Outcome")

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [3]:
# Preprocess numerical data for neural network

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [4]:
# Define the logistic regression model
log_classifier = LogisticRegression(solver="lbfgs",max_iter=200)

# Train the model
log_classifier.fit(X_train,y_train)

# Evaluate the model
y_pred = log_classifier.predict(X_test)
print(f" Logistic regression model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Logistic regression model accuracy: 0.729

In [5]:
# Define the basic neural network model
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=8))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
18/18 [==============================] - 0s 648us/step - loss: 0.7185 - accuracy: 0.4688
Epoch 2/50
18/18 [==============================] - 0s 706us/step - loss: 0.6830 - accuracy: 0.5451
Epoch 3/50
18/18 [==============================] - 0s 648us/step - loss: 0.6568 - accuracy: 0.5972
Epoch 4/50
18/18 [==============================] - 0s 648us/step - loss: 0.6330 - accuracy: 0.6337
Epoch 5/50
18/18 [==============================] - 0s 589us/step - loss: 0.6140 - accuracy: 0.6632
Epoch 6/50
18/18 [==============================] - 0s 648us/step - loss: 0.5969 - accuracy: 0.7049
Epoch 7/50
18/18 [==============================] - 0s 589us/step - loss: 0.5827 - accuracy: 0.7135
Epoch 8/50
18/18 [==============================] - 0s 648us/step - loss: 0.5699 - accuracy: 0.7361
Epoch 9/50
18/18 [==============================] - 0s 589us/step - loss: 0.5582 - accuracy: 0.7483
Epoch 10/50
18/18 [==============================] - 0s 648us/step - loss: 0.5478 - accuracy: 0.7552
Epoch 11/50
18/18 [==============================] - 0s 589us/step - loss: 0.5382 - accuracy: 0.7604
Epoch 12/50
18/18 [==============================] - 0s 648us/step - loss: 0.5292 - accuracy: 0.7691
Epoch 13/50
18/18 [==============================] - 0s 589us/step - loss: 0.5214 - accuracy: 0.7691
Epoch 14/50
18/18 [==============================] - 0s 589us/step - loss: 0.5145 - accuracy: 0.7726
Epoch 15/50
18/18 [==============================] - 0s 648us/step - loss: 0.5081 - accuracy: 0.7691
Epoch 16/50
18/18 [==============================] - 0s 589us/step - loss: 0.5022 - accuracy: 0.7743
Epoch 17/50
18/18 [==============================] - 0s 589us/step - loss: 0.4967 - accuracy: 0.7760
Epoch 18/50
18/18 [==============================] - 0s 589us/step - loss: 0.4918 - accuracy: 0.7760
Epoch 19/50
18/18 [==============================] - 0s 648us/step - loss: 0.4867 - accuracy: 0.7847
Epoch 20/50
18/18 [==============================] - 0s 619us/step - loss: 0.4827 - accuracy: 0.7899
Epoch 21/50
18/18 [==============================] - 0s 589us/step - loss: 0.4790 - accuracy: 0.7899
Epoch 22/50
18/18 [==============================] - 0s 707us/step - loss: 0.4754 - accuracy: 0.7865
Epoch 23/50
18/18 [==============================] - 0s 648us/step - loss: 0.4726 - accuracy: 0.7917
Epoch 24/50
18/18 [==============================] - 0s 588us/step - loss: 0.4691 - accuracy: 0.7934
Epoch 25/50
18/18 [==============================] - 0s 648us/step - loss: 0.4666 - accuracy: 0.7934
Epoch 26/50
18/18 [==============================] - 0s 589us/step - loss: 0.4644 - accuracy: 0.7934
Epoch 27/50
18/18 [==============================] - 0s 648us/step - loss: 0.4621 - accuracy: 0.7934
Epoch 28/50
18/18 [==============================] - 0s 648us/step - loss: 0.4602 - accuracy: 0.7934
Epoch 29/50
18/18 [==============================] - 0s 707us/step - loss: 0.4589 - accuracy: 0.7899
Epoch 30/50
18/18 [==============================] - 0s 589us/step - loss: 0.4568 - accuracy: 0.7969
Epoch 31/50
18/18 [==============================] - 0s 648us/step - loss: 0.4556 - accuracy: 0.7951
Epoch 32/50
18/18 [==============================] - 0s 707us/step - loss: 0.4542 - accuracy: 0.7934
Epoch 33/50
18/18 [==============================] - 0s 648us/step - loss: 0.4532 - accuracy: 0.7917
Epoch 34/50
18/18 [==============================] - 0s 707us/step - loss: 0.4519 - accuracy: 0.7934
Epoch 35/50
18/18 [==============================] - 0s 589us/step - loss: 0.4509 - accuracy: 0.7951
Epoch 36/50
18/18 [==============================] - 0s 707us/step - loss: 0.4499 - accuracy: 0.7951
Epoch 37/50
18/18 [==============================] - 0s 707us/step - loss: 0.4490 - accuracy: 0.7951
Epoch 38/50
18/18 [==============================] - 0s 648us/step - loss: 0.4482 - accuracy: 0.7969
Epoch 39/50
18/18 [==============================] - 0s 648us/step - loss: 0.4476 - accuracy: 0.7969
Epoch 40/50
18/18 [==============================] - 0s 589us/step - loss: 0.4467 - accuracy: 0.7969
Epoch 41/50
18/18 [==============================] - 0s 765us/step - loss: 0.4456 - accuracy: 0.7986
Epoch 42/50
18/18 [==============================] - 0s 707us/step - loss: 0.4449 - accuracy: 0.7969
Epoch 43/50
18/18 [==============================] - 0s 648us/step - loss: 0.4443 - accuracy: 0.7969
Epoch 44/50
18/18 [==============================] - 0s 648us/step - loss: 0.4438 - accuracy: 0.7986
Epoch 45/50
18/18 [==============================] - 0s 589us/step - loss: 0.4431 - accuracy: 0.7986
Epoch 46/50
18/18 [==============================] - 0s 589us/step - loss: 0.4427 - accuracy: 0.8021
Epoch 47/50
18/18 [==============================] - 0s 648us/step - loss: 0.4419 - accuracy: 0.8003
Epoch 48/50
18/18 [==============================] - 0s 589us/step - loss: 0.4415 - accuracy: 0.8021
Epoch 49/50
18/18 [==============================] - 0s 707us/step - loss: 0.4413 - accuracy: 0.8038
Epoch 50/50
18/18 [==============================] - 0s 589us/step - loss: 0.4411 - accuracy: 0.8003
6/6 - 0s - loss: 0.5048 - accuracy: 0.7188 - 113ms/epoch - 19ms/step
Loss: 0.5048301219940186, Accuracy: 0.71875

In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import tensorflow as tf

# Import our input dataset
tele_df = pd.read_csv('bank_telemarketing.csv')
tele_df.head()

,Age,Job,Marital_Status,Education,Default_Credit,Housing_Loan,Personal_Loan,Subscribed
0,56,other,married,Primary_Education,no,no,no,no
1,37,services,married,Secondary_Education,no,yes,no,no
2,40,admin,married,Primary_Education,no,no,no,no
3,56,services,married,Secondary_Education,no,no,yes,no
4,59,admin,married,Professional_Education,no,no,no,no

In [7]:
# Generate our categorical variable list
tele_cat = tele_df.dtypes[tele_df.dtypes == "object"].index.tolist()


# Check the number of unique values in each column
tele_df[tele_cat].nunique()

Job               9
Marital_Status    3
Education         4
Default_Credit    2
Housing_Loan      2
Personal_Loan     2
Subscribed        2
dtype: int64

In [8]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(tele_df[tele_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(tele_cat)
encode_df.head()

C:\Users\pcurl\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,Marital_Status_divorced,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [9]:
# Merge one-hot encoded features and drop the originals
tele_df = tele_df.merge(encode_df,left_index=True, right_index=True)
tele_df = tele_df.drop(tele_cat,1)
tele_df.head()

C:\Users\pcurl\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Age,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,56,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,40,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,59,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [10]:
# Remove loan status target from features data
y = tele_df.Subscribed_yes.values
X = tele_df.drop(columns=["Subscribed_no","Subscribed_yes"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [11]:
# Create the SVM model
svm = SVC(kernel='linear')

In [12]:
# Train the model
svm.fit(X_train, y_train)

SVC(kernel='linear')

In [13]:
# Evaluate the model
y_pred = svm.predict(X_test_scaled)
print(f" SVM model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 SVM model accuracy: 0.873

In [14]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model 
fit_model = nn.fit(X_train_scaled, y_train, epochs=50) 
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
715/715 [==============================] - 1s 684us/step - loss: 0.4210 - accuracy: 0.8551
Epoch 2/50
715/715 [==============================] - 0s 697us/step - loss: 0.3731 - accuracy: 0.8735
Epoch 3/50
715/715 [==============================] - 0s 676us/step - loss: 0.3708 - accuracy: 0.8735
Epoch 4/50
715/715 [==============================] - 0s 692us/step - loss: 0.3698 - accuracy: 0.8735
Epoch 5/50
715/715 [==============================] - 0s 692us/step - loss: 0.3691 - accuracy: 0.8735
Epoch 6/50
715/715 [==============================] - 0s 690us/step - loss: 0.3686 - accuracy: 0.8735
Epoch 7/50
715/715 [==============================] - 1s 751us/step - loss: 0.3682 - accuracy: 0.8735
Epoch 8/50
715/715 [==============================] - 1s 742us/step - loss: 0.3680 - accuracy: 0.8735
Epoch 9/50
715/715 [==============================] - 1s 747us/step - loss: 0.3677 - accuracy: 0.8735
Epoch 10/50
715/715 [==============================] - 1s 739us/step - loss: 0.3675 - accuracy: 0.8735
Epoch 11/50
715/715 [==============================] - 1s 708us/step - loss: 0.3673 - accuracy: 0.8735
Epoch 12/50
715/715 [==============================] - 0s 691us/step - loss: 0.3672 - accuracy: 0.8735
Epoch 13/50
715/715 [==============================] - 0s 686us/step - loss: 0.3670 - accuracy: 0.8735
Epoch 14/50
715/715 [==============================] - 0s 676us/step - loss: 0.3668 - accuracy: 0.8735
Epoch 15/50
715/715 [==============================] - 1s 711us/step - loss: 0.3665 - accuracy: 0.8735
Epoch 16/50
715/715 [==============================] - 1s 711us/step - loss: 0.3664 - accuracy: 0.8735
Epoch 17/50
715/715 [==============================] - 0s 681us/step - loss: 0.3663 - accuracy: 0.8735
Epoch 18/50
715/715 [==============================] - 0s 694us/step - loss: 0.3662 - accuracy: 0.8735
Epoch 19/50
715/715 [==============================] - 0s 691us/step - loss: 0.3659 - accuracy: 0.8735
Epoch 20/50
715/715 [==============================] - 0s 694us/step - loss: 0.3656 - accuracy: 0.8735
Epoch 21/50
715/715 [==============================] - 0s 690us/step - loss: 0.3654 - accuracy: 0.8734
Epoch 22/50
715/715 [==============================] - 0s 676us/step - loss: 0.3651 - accuracy: 0.8734
Epoch 23/50
715/715 [==============================] - 0s 684us/step - loss: 0.3649 - accuracy: 0.8733
Epoch 24/50
715/715 [==============================] - 0s 685us/step - loss: 0.3648 - accuracy: 0.8734
Epoch 25/50
715/715 [==============================] - 1s 700us/step - loss: 0.3648 - accuracy: 0.8735
Epoch 26/50
715/715 [==============================] - 0s 698us/step - loss: 0.3647 - accuracy: 0.8733
Epoch 27/50
715/715 [==============================] - 1s 707us/step - loss: 0.3643 - accuracy: 0.8734
Epoch 28/50
715/715 [==============================] - 0s 696us/step - loss: 0.3643 - accuracy: 0.8733
Epoch 29/50
715/715 [==============================] - 0s 682us/step - loss: 0.3643 - accuracy: 0.8736
Epoch 30/50
715/715 [==============================] - 0s 675us/step - loss: 0.3639 - accuracy: 0.8734
Epoch 31/50
715/715 [==============================] - 0s 686us/step - loss: 0.3639 - accuracy: 0.8736
Epoch 32/50
715/715 [==============================] - 0s 676us/step - loss: 0.3638 - accuracy: 0.8734
Epoch 33/50
715/715 [==============================] - 0s 681us/step - loss: 0.3638 - accuracy: 0.8733
Epoch 34/50
715/715 [==============================] - 0s 688us/step - loss: 0.3636 - accuracy: 0.8736
Epoch 35/50
715/715 [==============================] - 0s 676us/step - loss: 0.3635 - accuracy: 0.8737
Epoch 36/50
715/715 [==============================] - 0s 687us/step - loss: 0.3635 - accuracy: 0.8734
Epoch 37/50
715/715 [==============================] - 0s 677us/step - loss: 0.3633 - accuracy: 0.8733
Epoch 38/50
715/715 [==============================] - 0s 670us/step - loss: 0.3633 - accuracy: 0.8738
Epoch 39/50
715/715 [==============================] - 0s 673us/step - loss: 0.3632 - accuracy: 0.8734
Epoch 40/50
715/715 [==============================] - 0s 669us/step - loss: 0.3630 - accuracy: 0.8733
Epoch 41/50
715/715 [==============================] - 0s 678us/step - loss: 0.3631 - accuracy: 0.8736
Epoch 42/50
715/715 [==============================] - 0s 670us/step - loss: 0.3631 - accuracy: 0.8732
Epoch 43/50
715/715 [==============================] - 0s 676us/step - loss: 0.3630 - accuracy: 0.8736
Epoch 44/50
715/715 [==============================] - 1s 711us/step - loss: 0.3629 - accuracy: 0.8735
Epoch 45/50
715/715 [==============================] - 0s 688us/step - loss: 0.3631 - accuracy: 0.8734
Epoch 46/50
715/715 [==============================] - 0s 667us/step - loss: 0.3628 - accuracy: 0.8731
Epoch 47/50
715/715 [==============================] - 0s 684us/step - loss: 0.3627 - accuracy: 0.8736
Epoch 48/50
715/715 [==============================] - 0s 678us/step - loss: 0.3624 - accuracy: 0.8736
Epoch 49/50
715/715 [==============================] - 0s 679us/step - loss: 0.3626 - accuracy: 0.8734
Epoch 50/50
715/715 [==============================] - 0s 682us/step - loss: 0.3625 - accuracy: 0.8735
239/239 - 0s - loss: 0.3706 - accuracy: 0.8723 - 209ms/epoch - 875us/step
Loss: 0.37063997983932495, Accuracy: 0.872309684753418